### ISSUE TITLE
Runner fails with big url lists (like a whole sitemap with > 100 links)

### ISSUE THREAD

**Issue by oliverfriedmann** [jamesseanwright/valimate#3]
Validating URLs from valimate.json...

/usr/local/lib/node_modules/valimate/lib/services/httpService.js:43
		return response.statusCode >= 400;
		               ^

TypeError: Cannot read property 'statusCode' of undefined
    at Object._hasRequestFailed (/usr/local/lib/node_modules/valimate/lib/services/httpService.js:43:18)
    at Request._callback (/usr/local/lib/node_modules/valimate/lib/services/httpService.js:19:14)
    at self.callback (/usr/local/lib/node_modules/valimate/node_modules/request/request.js:187:22)
    at emitOne (events.js:78:13)
    at Request.emit (events.js:170:7)
    at Request.onRequestError (/usr/local/lib/node_modules/valimate/node_modules/request/request.js:813:8)
    at emitOne (events.js:78:13)
    at ClientRequest.emit (events.js:170:7)
    at Socket.socketErrorListener (_http_client.js:266:9)
    at emitOne (events.js:78:13)
Warning: Command failed: /bin/sh -c valimate
/usr/local/lib/node_modules/valimate/lib/services/httpService.js:43
		return response.statusCode >= 400;
		               ^

TypeError: Cannot read property 'statusCode' of undefined
    at Object._hasRequestFailed (/usr/local/lib/node_modules/valimate/lib/services/httpService.js:43:18)
    at Request._callback (/usr/local/lib/node_modules/valimate/lib/services/httpService.js:19:14)
    at self.callback (/usr/local/lib/node_modules/valimate/node_modules/request/request.js:187:22)
    at emitOne (events.js:78:13)
    at Request.emit (events.js:170:7)
    at Request.onRequestError (/usr/local/lib/node_modules/valimate/node_modules/request/request.js:813:8)
    at emitOne (events.js:78:13)
    at ClientRequest.emit (events.js:170:7)
    at Socket.socketErrorListener (_http_client.js:266:9)
    at emitOne (events.js:78:13)
 Use --force to continue.

OR:

Validating URLs from valimate.json...

[Error: Request to  failed with HTTP undefined]
[TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined]

Warning: Command failed: /bin/sh -c valimate
[Error: Request to  failed with HTTP undefined]
[TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined]
 Use --force to continue.

**Comment by jamesseanwright** [comment]
Hey Oliver,

Apologies for not responding, GitHub never notifies me of new issues! :/ Which version of Node.js are you running?

**Comment by jamesseanwright** [comment]
```
request(requestOptions, (err, response, body) => { 
	if (this._hasRequestFailed(response)) {
		reject(new Error(`Request to ${response.url} failed with HTTP ${response.status}`));
		return;
	}

	resolve(body);
});
```

Looks like I'm not handling the case in which `err` is truthy, which is a big oversight on my part; I can only apologies for this. I'll fix this now. In the meantime, please could submit your valimate.json config file to me as a comment?

Thanks,
James

**Comment by oliverfriedmann** [comment]
Node v5.2.0 - I switched to a more local approach without querying the w3c validator. It looks like I was just banned for hitting their servers too often, too quickly...

**Comment by jamesseanwright** [comment]
Fair enough. It's still obvious that I wasn't handling non-HTTP errors reported by request, so I'll still release a new version and ping you when it's out. Thanks again for bringing this to my attention. :)

Turns out I had somehow unwatched my own repo, hence the lack of notifications when issues are raised. This is now resolved for a speedier response to future issues.

**Comment by jamesseanwright** [comment]
I've now release 2.1.0. The corresponding tag (commit [8c705ae9e91bb0d9dd0ac62ef828460c09493090](https://github.com/jamesseanwright/valimate/commit/8c705ae9e91bb0d9dd0ac62ef828460c09493090) details the changes I've made.
